# Generated by Django 5.1.7 on 2025-06-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(max_length=128)),
                ('session_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='semantickeyword',
            name='alias',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campusbuilding',
            name='alias',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='GPTMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mychat.gptsession')),
            ],
        ),
    ]
