# Generated by Django 5.1.7 on 2025-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0002_gptsession_semantickeyword_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusbuilding',
            name='alias',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='semantickeyword',
            name='alias',
            field=models.CharField(max_length=100),
        ),
    ]
