# Generated by Django 5.1.7 on 2025-07-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0003_alter_campusbuilding_alias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusBuildingKeywordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mychat.campusbuilding')),
            ],
        ),
    ]
