# Generated by Django 5.1.7 on 2025-07-22 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0004_campusbuildingkeywordrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='mychat.campusbuilding')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityKeywordRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mychat.facility')),
            ],
        ),
    ]
