# Generated by Django 5.1.7 on 2025-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0005_facility_facilitykeywordrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='campusbuilding',
            name='floors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campusbuilding',
            name='alias',
            field=models.CharField(max_length=300),
        ),
    ]
