# Generated by Django 5.1.7 on 2025-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0006_campusbuilding_floors_alter_campusbuilding_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campusbuilding',
            name='floors',
        ),
        migrations.AlterField(
            model_name='campusbuilding',
            name='alias',
            field=models.CharField(max_length=100),
        ),
    ]
